import { Pet, Species, Gender, Size, AgeGroup } from './types';

export const PETS_DATA: Pet[] = [
  {
    id: '1',
    name: 'Paçoca',
    species: Species.Dog,
    breed: 'Vira-lata Caramelo',
    age: 2,
    ageGroup: AgeGroup.Adult,
    gender: Gender.Male,
    size: Size.Medium,
    location: 'São Paulo, SP',
    description: 'Um companheiro leal e cheio de energia para suas caminhadas.',
    story: 'Paçoca foi resgatado próximo a uma padaria. Ele é extremamente sociável, adora crianças e se dá bem com outros cachorros. Já está castrado e vacinado, pronto para encher sua casa de alegria.',
    imageUrl: 'https://picsum.photos/seed/pacoca/600/600',
    attributes: ['Castrado', 'Vacinado', 'Dócil', 'Gosta de Crianças'],
    isUrgent: false,
    isNew: true
  },
  {
    id: '2',
    name: 'Luna',
    species: Species.Cat,
    breed: 'Siamês',
    age: 1,
    ageGroup: AgeGroup.Adult,
    gender: Gender.Female,
    size: Size.Small,
    location: 'Rio de Janeiro, RJ',
    description: 'Elegante, tranquila e adora um sachê.',
    story: 'Luna é uma gatinha muito carinhosa que adora dormir no sol. Ela é um pouco tímida no início, mas depois que ganha confiança, não sai do seu colo.',
    imageUrl: 'https://picsum.photos/seed/luna/600/600',
    attributes: ['Vacinada', 'Castrada', 'Apartamento', 'Calma'],
    isUrgent: true,
    isNew: false
  },
  {
    id: '3',
    name: 'Thor',
    species: Species.Dog,
    breed: 'Labrador Mix',
    age: 0,
    ageGroup: AgeGroup.Puppy,
    gender: Gender.Male,
    size: Size.Large,
    location: 'Curitiba, PR',
    description: 'Um gigante gentil que ainda está aprendendo sobre o mundo.',
    story: 'Thor é um bebezão. Apesar do tamanho, acha que é um cachorro de colo. Precisa de espaço para correr e gastar energia.',
    imageUrl: 'https://picsum.photos/seed/thor/600/600',
    attributes: ['Vacinado', 'Brincalhão', 'Precisa de Quintal'],
    isUrgent: false,
    isNew: true
  },
  {
    id: '4',
    name: 'Mimi',
    species: Species.Cat,
    breed: 'SRD',
    age: 8,
    ageGroup: AgeGroup.Senior,
    gender: Gender.Female,
    size: Size.Small,
    location: 'Belo Horizonte, MG',
    description: 'Uma senhora distinta procurando um sofá quentinho.',
    story: 'Mimi perdeu sua tutora antiga e busca um lar calmo para passar seus anos dourados. Ela é extremamente afetuosa e ronrona alto.',
    imageUrl: 'https://picsum.photos/seed/mimi/600/600',
    attributes: ['Castrada', 'Vacinada', 'Ideal para Idosos'],
    isUrgent: true,
    isNew: false
  },
  {
    id: '5',
    name: 'Bob',
    species: Species.Dog,
    breed: 'Poodle',
    age: 4,
    ageGroup: AgeGroup.Adult,
    gender: Gender.Male,
    size: Size.Small,
    location: 'Campinas, SP',
    description: 'Inteligente, hipoalergênico e adora brincar de buscar.',
    story: 'Bob é o cão perfeito para apartamento. Não late muito, é limpo e adora aprender truques novos.',
    imageUrl: 'https://picsum.photos/seed/bob/600/600',
    attributes: ['Castrado', 'Adestrado', 'Apartamento'],
    isUrgent: false,
    isNew: false
  },
  {
    id: '6',
    name: 'Frida',
    species: Species.Dog,
    breed: 'Bulldog Francês',
    age: 3,
    ageGroup: AgeGroup.Adult,
    gender: Gender.Female,
    size: Size.Small,
    location: 'São Paulo, SP',
    description: 'Cheia de personalidade e roncos engraçados.',
    story: 'Frida é uma figura. Adora ser o centro das atenções e não gosta muito de dividir seus brinquedos, por isso seria ideal ser filha única.',
    imageUrl: 'https://picsum.photos/seed/frida/600/600',
    attributes: ['Castrada', 'Vacinada', 'Personalidade Forte'],
    isUrgent: false,
    isNew: true
  }
];
